### ISSUE TITLE
Debian inclusion

### ISSUE THREAD

**Issue by Fantu** [linuxmint/aptkit#4]
I opened an [RFP](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1081742) on Debian, but I open also here for more visibility.

I would like it to be included in Debian 13, but I'm afraid I don't have enough time to manage other packages properly, so I'll try to open this one in the hope that someone else is interested.

**Comment by julian-klode** [comment]
Please consider renaming the project to avoid the apt name. As the APT maintainers we are strongly opposed to any further intrusion into the apt namespace, and have and will continue to fight any such intrusion in Debian. Any such package creates a burden for the APT team who gets blamed and consulted for bugs and requests in those packages, and we don't want that.

**Comment by Fantu** [comment]
@clefebvre read above^

**Comment by clefebvre** [comment]
Does captain need to be renamed as well? How about qapt-deb-installer, apt-clone, synaptic, aptly, aptfs, apt-mirror?

These are all named apt something, not because they are APT, but because they provide APT-related features.

**Comment by clefebvre** [comment]
![image](https://github.com/user-attachments/assets/b1117b9b-0c76-4c38-8a6e-baa81ff51ede)

@Fantu ^^ 

This shows a bigger issue than just the naming or the python-defer dependency. Julian thinks aptdaemon/aptkit shouldn't exist at all. That's not something we can fix :) It doesn't look like it will make it into Debian no matter what we do.

I'm also interpreting this as Julian planning to make his own solution. That's really bad timing, but hey it's also very good news long-term.

We'll use aptkit until his solution is ready (because we really do need it). When APT provides its own deamon, hopefully by the time we reach the next LTS, then we'll switch to it and discontinue aptkit.

**Comment by Fantu** [comment]
As suggested 2 weeks ago:

> I think that can be useful write an email on debian-devel about this project and what you want to do to get any opinions, advice and if there is any Debian developer interested maybe join.

so maybe you could find out this before and maybe you could get answers from more people, maybe with useful information on what you want to do

----------------------

I think it's good to talk/write anyway and collaborate in order to improve existing software if possible and avoid new forks or new software if possible. This is general advice, not just for this one.
With less fragmentation, more collaboration in larger projects with many people you can achieve better results than in multiple small projects with limited resources.

Regarding this, I think you should make known any shortcomings or problems found in many years on Mint (with existing tools and that you try to fill with aptkit) to see if they will be included or solved in what they want to do (in packagekit and future apt own daemon).
Maybe some things are not communicated by anyone and they do not think about them.

**Comment by clefebvre** [comment]
Absolutely. It'll be our pleasure. We're using apt-python, aptdaemon and packagekit a lot so don't hesitate to come chat with us whenever you make the next great thing to make sure nothing important is missing.

Good luck.

**Comment by Fantu** [comment]
It's great that you are open to collaboration (unfortunately, there are many who don't want to do it, to their own detriment, or even more so to the users of both software).

More exactly what I meant is you should contact them, if you haven't already.
In some cases developers of a certain software take a look downstream (for example packages in distros), users who talk about that software in forums, blogs etc... to find possible bugs and improvements not communicated directly upstream; but it is not said that everyone does it or has the time to do it.
So it is important to inform them directly (in upstream bugtracker, mailing list etc... based on what should be better) of any bugs, shortcomings or possible improvements to recommend.

**Comment by Fantu** [comment]
Today while I was replying to a discussion this discussion came to mind and rereading I thought I'd try to open a PR in packagekit about the addition you made to see if with that we can get improvements both for upstream (and all those who use it) and for Mint
